[package]
name = "recto"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
anyhow = "1"
color-eyre = "0.6"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }
notify = "8.2.0"
clap = { version = "4", features = ["derive"] }
similar = "2"
